[package]
name = "buffengine"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
fern = "0.6"
humantime = "2.1"
bitmask-enum = "2.2.4"
winit = "0.30.8"
wgpu = "24.0.1"
pollster = "0.4.0"
bytemuck = { version = "1.21.0", features = ["derive"] }
image = "0.25.6"
glam = "0.30.4"
